version: '3.5'

services:
  postgres:
    container_name: bot_db
    image: postgres:14.3-alpine
    expose:
      - "5432"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_UESR=admin
      